---
# tasks file for node_exporter
- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz

- name: Unzip the Node Exporter package
  ansible.builtin.unarchive:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Node Exporter binary to /usr/local/bin
  ansible.builtin.command:
    cmd: mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: Create Node Exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started
